version: '3.7'

services:
  configserver:
    image: msa/config-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"

  diaryservice:
    image: msa/diary-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
      CONFIG_SERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      - configserver
    networks:
      - backend

networks:
  backend:
    driver: bridge
