version: '3.7'

services:
  configserver:
    image: msa/config-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    image: msa/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    depends_on:
      - configserver
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image: msa/gateway-server:0.0.1-SNAPSHOT
    ports:
      - "8062:8062"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8062"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      backend:
        aliases:
          - "gateway"

  diaryservice:
    image: msa/diary-service:0.0.2-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      - configserver
    networks:
      - backend

  writerservice:
    image: msa/writer-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      profile: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      - configserver
    networks:
      - backend

networks:
  backend:
    driver: bridge
